"""Regenerate us_market_core/etf_universe.py - the ETF side of the board.

The groups are hand-curated and deliberate; only the LABELS are fetched, so a
Yahoo hiccup can change a display name but can never change what the board
covers.

WHY THE GROUPS EXIST AT ALL - and a correction worth recording. They are NOT
a normalisation device. rrg_tail z-scores each symbol over ITS OWN history, so
what a bubble shows does not depend on what else is plotted beside it; putting
SHV (a 3-month T-bill fund that barely moves) on the same chart as SOXX
distorts neither of them. The groups exist for two plainer reasons: 112 ETFs
and 503 stocks on one canvas is unreadable, and a group is the unit you
actually think in when reading rotation - bonds against equities, defensives
against cyclicals. Switching group is switching question, not switching scale.

Sector SPDRs are special-cased: they are the eleven GICS sectors as tradeable
funds, so they double as the sector view's series. That is better than an
equal-weight basket of constituents (what the Indian board must build, lacking
a liquid sectoral index per group) because it is the thing you can actually
buy, with real weights.
"""

import os
import sys

import requests

HEADERS = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "us_market_core", "etf_universe.py")

# Groups are curated. Order within a group is display order.
ETF_GROUPS = {
    "Sector SPDR": ["XLK", "XLF", "XLV", "XLY", "XLP", "XLE", "XLI", "XLB",
                    "XLRE", "XLU", "XLC"],
    "Broad market": ["SPY", "QQQ", "IWM", "DIA", "RSP", "MDY", "VTI", "VOO", "QQQE"],
    "Style & factor": ["IWF", "IWD", "MTUM", "QUAL", "USMV", "SPLV", "VLUE",
                       "SIZE", "SPHQ", "PFF"],
    "Industry & theme": ["SMH", "SOXX", "IGV", "XBI", "IBB", "ITB", "XHB", "KRE",
                         "KBE", "XOP", "OIH", "JETS", "ARKK", "TAN", "ICLN",
                         "LIT", "URA", "XAR", "PPA", "HACK", "IHI", "XRT",
                         "XME", "XLG", "BOTZ", "ROBO", "CIBR", "FDN", "SKYY",
                         "BLOK"],
    "Fixed income": ["TLT", "IEF", "SHY", "LQD", "HYG", "TIP", "AGG", "BND",
                     "MBB", "EMB", "BKLN", "SHV"],
    "Commodity & FX": ["GLD", "SLV", "IAU", "GDX", "GDXJ", "USO", "UNG", "DBC",
                       "DBA", "UUP", "FXE", "PPLT", "COPX"],
    "Country & region": ["EFA", "EEM", "VGK", "EWJ", "EWZ", "EWW", "INDA",
                         "MCHI", "FXI", "EWY", "EWT", "EWU", "EWG", "EWC",
                         "EIS", "KWEB", "ILF", "ACWX", "VEA", "VWO", "EZU", "EPI"],
    "Crypto-linked": ["IBIT", "BITO", "ETHA", "BITQ", "FBTC"],
}

# The eleven Select Sector SPDRs ARE the GICS sectors, as funds.
SECTOR_ETF = {
    "Information Technology": "XLK",
    "Financials": "XLF",
    "Health Care": "XLV",
    "Consumer Discretionary": "XLY",
    "Consumer Staples": "XLP",
    "Energy": "XLE",
    "Industrials": "XLI",
    "Materials": "XLB",
    "Real Estate": "XLRE",
    "Utilities": "XLU",
    "Communication Services": "XLC",
}


def probe(t):
    url = (f"https://query1.finance.yahoo.com/v8/finance/chart/{t}"
           "?interval=1d&range=5y")
    r = requests.get(url, headers=HEADERS, timeout=25)
    if r.status_code != 200:
        return None, f"HTTP {r.status_code}"
    d = r.json()["chart"]["result"][0]
    closes = [c for c in d["indicators"]["quote"][0]["close"] if c is not None]
    meta = d["meta"]
    name = meta.get("shortName") or meta.get("longName") or t
    if meta.get("currency") != "USD":
        return None, f"currency {meta.get('currency')}"
    return (name.strip(), len(closes)), None


def main():
    flat = [t for g in ETF_GROUPS.values() for t in g]
    dupes = {t for t in flat if flat.count(t) > 1}
    if dupes:
        print(f"ABORTING - ticker in more than one group: {sorted(dupes)}",
              file=sys.stderr)
        sys.exit(1)
    missing = sorted(set(SECTOR_ETF.values()) - set(ETF_GROUPS["Sector SPDR"]))
    if missing:
        print(f"ABORTING - SECTOR_ETF names not in the Sector SPDR group: {missing}",
              file=sys.stderr)
        sys.exit(1)

    names, bars, fail = {}, {}, {}
    for t in flat:
        got, err = probe(t)
        if err:
            fail[t] = err
        else:
            names[t], bars[t] = got
    if fail:
        print("ABORTING - every curated ETF must resolve on Yahoo:", file=sys.stderr)
        for t, e in sorted(fail.items()):
            print(f"  - {t}: {e}", file=sys.stderr)
        sys.exit(1)

    with open(OUT, "w") as f:
        f.write('"""GENERATED by scripts/refresh_etfs.py - do not hand-edit.\n\n'
                "Groups are curated in that script; labels come from Yahoo.\n"
                '"""\n\n')
        f.write("ETF_GROUPS = {\n")
        for g, ts in ETF_GROUPS.items():
            f.write(f'    "{g}": {ts!r},\n')
        f.write("}\n\nSECTOR_ETF = {\n")
        for k, v in SECTOR_ETF.items():
            f.write(f'    "{k}": "{v}",\n')
        f.write("}\n\nETF_NAME = {\n")
        for t in flat:
            f.write(f'    "{t}": "{names[t]}",\n')
        f.write("}\n")

    print(f"wrote {OUT}")
    for g, ts in ETF_GROUPS.items():
        print(f"   {len(ts):>3}  {g}")
    print(f"   {len(flat):>3}  TOTAL")
    thin = {t: n for t, n in bars.items() if n < 1000}
    print("\nunder 5y of history (will be excluded from the 5y views, by the "
          "existing minimum-history rule, not special-cased):")
    for t, n in sorted(thin.items(), key=lambda kv: kv[1]):
        print(f"   {t:<6} {n:>5} bars   {names[t]}")


if __name__ == "__main__":
    main()
