"""Regenerate us_market_core/universe.py from two INDEPENDENT sources.

WHY TWO. The board's whole shape - which names exist, which sector each sits
in - comes from outside. A single source that quietly changes format, or
returns a truncated page, would shrink the board without failing anything.
So the S&P 500 list is fetched from the datasets.io CSV *and* parsed from
Wikipedia's constituents table, and the two must agree EXACTLY on both the
symbol set and every symbol's GICS sector. They did on 2026-10-05: 503 names,
11 sectors, zero disagreements. Any disagreement aborts and prints it, rather
than picking a winner - a silent tiebreak is how a universe goes stale.

Yahoo uses '-' where S&P uses '.' (BRK.B -> BRK-B). That mapping is applied
here, once, so nothing downstream has to remember it.

Run manually when the index rebalances; this is NOT part of the daily build.
A generated file is committed on purpose - the daily job must not depend on
Wikipedia being up.
"""

import csv
import io
import os
import re
import sys
from collections import Counter, defaultdict

import requests

HEADERS = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}
CSV_URL = ("https://raw.githubusercontent.com/datasets/s-and-p-500-companies"
           "/main/data/constituents.csv")
WIKI_URL = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "us_market_core", "universe.py")

GICS_SECTORS = [
    "Information Technology", "Health Care", "Financials",
    "Consumer Discretionary", "Communication Services", "Industrials",
    "Consumer Staples", "Energy", "Utilities", "Real Estate", "Materials",
]


def from_csv():
    txt = requests.get(CSV_URL, headers=HEADERS, timeout=30).text
    rows = list(csv.DictReader(io.StringIO(txt)))
    return ({r["Symbol"]: r["GICS Sector"] for r in rows},
            {r["Symbol"]: r["Security"] for r in rows})


def from_wiki():
    html = requests.get(WIKI_URL, headers=HEADERS, timeout=30).text
    i = html.find('id="constituents"')
    if i < 0:
        raise RuntimeError("Wikipedia constituents table not found")
    table = html[i: html.find("</table>", i)]
    out, names = {}, {}
    for row in re.findall(r"<tr[^>]*>(.*?)</tr>", table, re.S):
        cells = re.findall(r"<t[dh][^>]*>(.*?)</t[dh]>", row, re.S)
        if len(cells) < 4:
            continue
        txt = [re.sub(r"<[^>]+>", "", c).replace("&amp;", "&").strip() for c in cells]
        if not re.fullmatch(r"[A-Z][A-Z.\-]{0,6}", txt[0]):
            continue
        out[txt[0]], names[txt[0]] = txt[2], txt[1]
    return out, names


def main():
    a, a_names = from_csv()
    b, b_names = from_wiki()
    print(f"datasets.io : {len(a)} names")
    print(f"wikipedia   : {len(b)} names")

    fatal = []
    only_a, only_b = sorted(set(a) - set(b)), sorted(set(b) - set(a))
    if only_a:
        fatal.append(f"in datasets.io but not Wikipedia: {only_a}")
    if only_b:
        fatal.append(f"in Wikipedia but not datasets.io: {only_b}")
    dis = {k: (a[k], b[k]) for k in set(a) & set(b) if a[k] != b[k]}
    if dis:
        fatal.append(f"sector disagreements: {dis}")
    bad = sorted({s for s in a.values() if s not in GICS_SECTORS})
    if bad:
        fatal.append(f"unknown GICS sectors: {bad}")
    if len(a) < 490 or len(a) > 520:
        fatal.append(f"implausible constituent count {len(a)} (expected ~503)")
    if fatal:
        print("ABORTING - the two sources must agree exactly:", file=sys.stderr)
        for f in fatal:
            print(f"  - {f}", file=sys.stderr)
        sys.exit(1)
    print("both sources agree exactly; writing", OUT)

    by_sector = defaultdict(list)
    for sym, sec in a.items():
        by_sector[sec].append(sym)

    with open(OUT, "w") as f:
        f.write('"""GENERATED by scripts/refresh_universe.py - do not hand-edit.\n\n'
                "The S&P 500 by GICS sector, agreed by datasets.io and Wikipedia.\n"
                "Keys are Yahoo tickers ('.' already mapped to '-').\n"
                '"""\n\n')
        f.write("SPX_SECTORS = {\n")
        for sec in GICS_SECTORS:
            syms = sorted(by_sector[sec])
            f.write(f'    "{sec}": [\n')
            for i in range(0, len(syms), 6):
                chunk = ", ".join(f'"{s.replace(".", "-")}"' for s in syms[i:i + 6])
                f.write(f"        {chunk},\n")
            f.write("    ],\n")
        f.write("}\n\n")
        f.write("COMPANY = {\n")
        for sym in sorted(a):
            nm = a_names[sym].replace('"', "'")
            f.write(f'    "{sym.replace(".", "-")}": "{nm}",\n')
        f.write("}\n")

    for sec in GICS_SECTORS:
        print(f"   {len(by_sector[sec]):>3}  {sec}")
    print(f"   {sum(len(v) for v in by_sector.values()):>3}  TOTAL")


if __name__ == "__main__":
    main()
